name: deploy svelte to github pages

# Don't forget to add `base: './'` to your vite.config.ts file

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Setup base
      run: just init

    - name: Build
      run: |
        just build
        touch ./dist/.nojekyll

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./dist
